### ISSUE TITLE
Getting crashed during app run in Android 6.0. (Details inside)

### ISSUE THREAD

**Issue by NomanBaigA** [drmfinlay/tts-util-app#38]
I saw this error just after downloading and running the project on an Android 6.0 device.

Did a little change before run - "distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip" Also tried without changes

after this change, I got this error during the app run

2023-10-07 19:11:07.457  2589-2691  WorkSourceUtil          com.google.android.gms               E  Could not find package: com.danefinlay.ttsutil
2023-10-07 19:11:07.599  2589-9292  FA-SVC                  com.google.android.gms               E  Error deleting application data. appId, error: com.danefinlay.ttsutil, android.database.sqlite.SQLiteException: no such table: trigger_uris (code 1): , while compiling: DELETE FROM trigger_uris WHERE app_id=?: bgrr.w(:com.google.android.gms@233717019@23.37.17 (040400-570218080):100)
.
.
.
.
.
2023-10-07 19:11:53.933 10118-10198 JavaBinder              com.danefinlay.ttsutil               E  *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                                                                    java.lang.NoSuchMethodError: No super method onRangeStart(Ljava/lang/String;III)V in class Landroid/speech/tts/UtteranceProgressListener; or its super classes (declaration of 'android.speech.tts.UtteranceProgressListener' appears in /system/framework/framework.jar)
                                                                                                    	at com.danefinlay.ttsutil.TTSTask.onRangeStart(TTSTasks.kt:431)
                                                                                                    	at com.danefinlay.ttsutil.TTSTask.onStart(TTSTasks.kt:425)
                                                                                                    	at android.speech.tts.TextToSpeech$Connection$1.onStart(TextToSpeech.java:2106)
                                                                                                    	at android.speech.tts.ITextToSpeechCallback$Stub.onTransact(ITextToSpeechCallback.java:55)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:458)
.
.
.
.
2023-10-07 19:11:53.938 10118-10198 JavaBinder              com.danefinlay.ttsutil               E  Forcefully exiting
.

**Comment by NomanBaigA** [comment]
I tried it from F droid and it's working FINE but it's giving an error when I am trying it with the source code. WHY?

**Comment by drmfinlay** [comment]
Hello @NomanBaigA,

Thank you for opening this issue and pull request #37.

The reason that the current F-Droid version of *TTS Util* is working and the latest source code isn't is because I'm still plodding away on the next version of the app.  There are quite a few unreleased changes on the master branch.  My development focus has not been Android 6.0, so I didn't catch this error.  But, rest assured, I will make sure the app still works on that version prior to release.

Since you are interested enough to build my application, and even open a PR, I will say that the `onRangeStart()` method error in the log you provided above is occurring because Android 6.0 has no such method.  It was added later on, in Android 8.0.  Hence the unexpected crash.

**Comment by NomanBaigA** [comment]
> Hello @NomanBaigA,
> 
> Thank you for opening this issue and pull request #37.
> 
> The reason that the current F-Droid version of _TTS Util_ is working and the latest source code isn't is because I'm still plodding away on the next version of the app. There are quite a few unreleased changes on the master branch. My development focus has not been Android 6.0, so I didn't catch this error. But, rest assured, I will make sure the app still works on that version prior to release.
> 
> Since you are interested enough to build my application, and even open a PR, I will say that the `onRangeStart()` method error in the log you provided above is occurring because Android 6.0 has no such method. It was added later on, in Android 8.0. Hence the unexpected crash.

Thanks for your response, as I said when I am trying the app from the source code I am getting this error BUT when I am trying the same app from F droid it works fine, Which means there is nothing to do with versions here.

**Comment by drmfinlay** [comment]
I have built *TTS Util* version 4.0.2, the latest F-Droid version, from source (`git checkout v4.0.2`) with your Gradle distribution change.  I have installed and run that build on Android 6.0 and do not get a crash.

I don't know what else to say.  The app won't crash on Android 6.0 in the next release version.

**Comment by NomanBaigA** [comment]
> I have built _TTS Util_ version 4.0.2, the latest F-Droid version, from source (`git checkout v4.0.2`) with your Gradle distribution change. I have installed and run that build on Android 6.0 and do not get a crash.
> 
> I don't know what else to say. The app won't crash on Android 6.0 in the next release version.

Thanks, Now I tested with the provided zip file and its working fine
